---
- name: Download MongoDB exporter
  get_url:
    url: "{{ mongodb_exporter_download_url }}"
    dest: /tmp/mongodb_exporter.tar.gz

- name: Extract MongoDB exporter
  unarchive:
    src: /tmp/mongodb_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move MongoDB exporter binary to /usr/local/bin
  copy:
    src: /tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-amd64
    dest: "{{ mongodb_exporter_binary_path }}"
    mode: '0755'
    remote_src: true

- name: Create MongoDB Exporter service file
  template:
    src: mongodb_exporter.service.j2
    dest: "{{ mongodb_exporter_service_path }}"
    mode: '0644'

- name: Reload systemd to apply the new service
  systemd:
    daemon_reload: yes

- name: Start and enable MongoDB Exporter service
  systemd:
    name: mongodb_exporter
    enabled: yes
    state: started
